### ISSUE TITLE
Bootcamp feedback

### ISSUE THREAD

**Issue by scarioscia** [lws99/qbb2023-answers#1]
Day 1: **6/6**
1 pt - print out first and last days (exercise 1)
1 pt - calculate averages for all patients (exercise 2)
1 pt - print out first 10 averages (exercise 2)
1 pt - printed out max (exercise 3)
1 pt - printed out min (exercise 3)
1 pt - printed out differences between patients (exercise 4)

Day 2: **0/7 the code looks okay - please upload the plots to the same dierctory**
1pt - Plot female data
1pt - Add male data
1pt - Plotted two x female data
1 pt x axis label
1 pt y axis label
1 pt labelled each line using a legend
1 pt plot title

Day 3: **6/6**
1pt - Submitted mean.py  + code looks more or less ok
1pt - Submitted mean_from_file.py + code looks more or less ok
1pt - mean_inflammation.py contains function that calculates mean inflammation
1pt - mean_inflammation.py prints output (or at least function returns the man value)
1pt - difference_inflammation.py contains function that calculates the difference in inflammation
1pt difference_inflammation.py  prints output (or at least function returns the man value)
**Code looks great, and excellent use of code comments! For things where you're using `sys.argv`, it's useful to have a "usage" statement near the top of the script as a comment. E.g., `# Usage: ./mean_from_file.py inflammation-01.csv` so if you go back to the code at a later time, you can see exactly what the inputs were. This is especially helpful when you have multiple inputs (`sys.argv[2]`, `sys.argv[3]` etc. so you can clearly see which was which).** 

Day 4: **5/10 Code looks good and answers are great. Please upload all plots** 
1 pt - Wright-Fisher function (ex 1)
1 pt - number of generations (ex 1)
1 pt - plot of allele trajectory (ex 1)
1 pt - plot of multiple allele trajectories (ex 2)
1 pt - histogram of time to fixation (ex 2)
1 pt - plot of population size vs time to fixation (ex 3)
1 pt - plot of allele frequency vs time to fixation (ex 3)
3 pts - short written answers to 3 questions (comment on any 3 plots)

**Comment by scarioscia** [comment]
Day 2: 7/7
Day 4: 10/10 

Now that this assignment is done presumably to your satisfaction (since you got full credit) you can close the issue. Also in the future if you update your assignments you can reply in a comment to the issue and @ your TA so they know to come look. Nice work!

**Comment by lws99** [comment]
Sounds good! Thank you so much for your help and time on this!
